{{- /*
  Read in the RU configuration information from the configmap
*/}}
{{- $ru_list_yaml := $.Files.Get "extra-config.yaml" | fromYaml }}
{{/*- $configmap := (lookup "v1" "ConfigMap" "default" "ru-testconfig") */}}
{{/*- $ru_list_yaml := get $configmap.data "rulist.yaml" | fromYaml */}}

{{- /*
  Helm templating doesn't support math power operations, so we have to
  hardcode the gnb_id_length parameter. We include it as a parameter in
  values.yaml so if it is changed we can fail to alert the user that it
  needs updating in the helm chart directly.
*/ -}}
{{- if ne (int .Values.splitCUConf.gnb_id_length) 22 }}
  {{ fail "splitCUConf:gnb_id_length in values.yaml *must* be 22, otherwise templates/srsran-split/cu-conf.yaml must be updated" }}
{{ end -}}

{{- /*
  Create a list of all the RUs that should be included in this split
*/ -}}
{{ $radios := list }}
{{- range $desiredRadio := .Values.desiredRadios }}
  {{ if eq $desiredRadio.type "srsran-split" }}
    {{- range $radio := $ru_list_yaml.ru_list }}
      {{ if eq $radio.name $desiredRadio.name }}
        {{- /*
          This is the section that uses a hard-coded gnb_id_length. The full calculation should be
            NCI = gnb_id * 2^(36-gnb_id_length) + sector_id
          but helm doesn't support powers, so gnb_id_length has been hardcoded to 22, resulting in
          2^(36-22) == 16384. If the gnb_id_length is to be changed, this value must be updated.
        */ -}}
        {{ $_ := set $radio "nr_cell_id" (add (mul (int $.Values.splitCUConf.gnb_id) 16384) ($radio.vlan | int)) }}
        {{ $radios = append $radios $radio }}
      {{ end }}
    {{ end }}
  {{ end }}  
{{ end -}}

{{ if gt (len $radios) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: srsran-split-cu-config
  namespace: srsran-split
data:
  cu.conf: |
    gnb_id_bit_length: {{ .Values.splitCUConf.gnb_id_length }}
    gnb_id: {{ .Values.splitCUConf.gnb_id }}
    log:
      filename: stdout
      all_level: error
      ngap_level: info
      config_level: debug
      cu_level: debug
    pcap:
      f1ap_filename: __PCAP_DIR__/gnb_f1ap.pcap
      f1ap_enable: true
      e1ap_filename: __PCAP_DIR__/gnb_e1ap.pcap
      e1ap_enable: true
      ngap_filename: __PCAP_DIR__/gnb_ngap.pcap
      ngap_enable: true
    cu_cp:
      max_nof_dus: {{ len $radios }}
      request_pdu_session_timeout: 1
      amf:
        addr: {{ .Values.amf_ip }}
        port: 38412
        bind_addr: {{ .Values.splitCUConf.amf_bind_ip }}
        sctp_nodelay: false
        supported_tracking_areas:
        - tac: 1
          plmn_list:
          - plmn: "99999"
            tai_slice_support_list:
            - sst: 1
      f1ap:
        bind_addr: {{ .Values.splitCUConf.f1ap_bind_ip }}
      rrc:
        force_reestablishment_fallback: true
      mobility:
        trigger_handover_from_measurements: true
        cells:
        {{- range $radio := $radios }}
        - nr_cell_id: {{ $radio.nr_cell_id }}
          periodic_report_cfg_id: 1
          ncells:
          {{- range $neighbor := $radios }}
          {{- if ne $neighbor.name $radio.name }}
          - nr_cell_id: {{ $neighbor.nr_cell_id }}
          {{- end }}
          {{- end }}
        {{- end }}
        report_configs:
        - report_cfg_id: 1
          report_type: periodical
          event_triggered_report_type: a3
          meas_trigger_quantity: rsrp
          meas_trigger_quantity_offset_db: 2
          hysteresis_db: 2
          report_interval_ms: 480
          time_to_trigger_ms: 0
          periodic_ho_rsrp_offset_db: 2
        - report_cfg_id: 2
          report_type: event_triggered
          event_triggered_report_type: a3
          meas_trigger_quantity: rsrp
          meas_trigger_quantity_offset_db: 2
          hysteresis_db: 0
          time_to_trigger_ms: 100
          report_interval_ms: 1024
    cu_up:
      ngu:
        gtpu:
          queue_size: 8192
          batch_size: 512
      f1u:
        socket:
        - bind_addr: {{ .Values.splitCUConf.f1u_bind_ip }}
          ext_addr: auto
          udp:
            max_rx_msgs: 512
            pool_threshold: 1
    metrics:
      enable_log: false
      enable_json: true
      layers:
        enable_app_usage: true
        enable_pdcp: true
      periodicity:
        cu_cp_report_period: 1000
    imsv_metric: "10.105.253.161:55555"
    remote_control:
      bind_addr: 0.0.0.0
      enabled: true
      port: 55555
{{- end }}
